### ISSUE TITLE
Getting hello to work

### ISSUE THREAD

**Issue by polytypic** [xyncro/freya#191]
I made a quick attempt to get the hello example from

  https://docs.freya.io/en/latest/tutorials/getting-started.html

to work.  Here is the code:

  https://github.com/polytypic/freya-hello

What I expect is to get a `Hello World!` reply, but instead I get these:

```bash
$ curl -v http://localhost:7000/hello
*   Trying ::1...
* connect to ::1 port 7000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7000 (#0)
> GET /hello HTTP/1.1
> Host: localhost:7000
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Server: Mono-HTTPAPI/1.0
< Date: Thu, 08 Sep 2016 07:46:38 GMT
< Content-Length: 0
< Connection: close
< 
* Closing connection 0
```

```bash
$ curl -v http://127.0.0.1:7000/hello
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 7000 (#0)
> GET /hello HTTP/1.1
> Host: 127.0.0.1:7000
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Type: text/html; charset=utf-8
< Server: Mono-HTTPAPI/1.0
< Date: Thu, 08 Sep 2016 07:46:44 GMT
< Content-Length: 35
< Connection: close
< 
* Closing connection 0
<h1>Bad Request (Invalid host)</h1>
```

What am I doing wrong?

**Comment by polytypic** [comment]
After building and running [freya-examples](https://github.com/xyncro/freya-examples) and comparing the set of dll's it seems that the problem was missing `Freya.Polyfills.dll`.

**Comment by kolektiv** [comment]
That is interesting though, as the Hello World demo doesn't actually use the Polyfills at all (although the project in freya-examples does have a reference to it). I don't think it should need polyfills at all for just that code - so I'm going to check!

Good to see that you got it working, but sorry that it wasn't trivial! I'll look at that.

**Comment by polytypic** [comment]
I'm not sure what the exact set of dlls required is.  I initially just added dll references until it was possible to run the `app.fsx` script without it being terminated due to a missing dll error, but that does not seem to be enough to process requests correctly.  Now I've just added all the dlls used by the `freya-example`.

**Comment by kolektiv** [comment]
Although - the router does have a dependency on Freya.Polyfills - just not a specific server implementation. So it would need the dependency on Freya.Polyfills.dll (but not a dependency on anything like Freya.Polyfills.Katana.dll). The same applies to the Hopac versions. Hmmm.

Do you think it behaves as expected? And do you think there's anything I could add in terms of documentation, etc. to save you time in future similar situations?

**Comment by polytypic** [comment]
Hmm... A troubleshooting section that explains how to get info (without a debugger) when the server responds with 500 might have helped.

**Comment by kolektiv** [comment]
Yes, that's a pretty reasonable call. It's a bit of a sod because the error and doing anything about is generally inside either Katana, Kestrel, etc. and they're awful at signalling anything useful going on through their errors. But even a short section detailing known failure modes as people find them would at least give people a place to look and maybe save some time and pain.
