### ISSUE TITLE
Documentation or Examples on handling Cookies

### ISSUE THREAD

**Issue by ptrelford** [xyncro/freya#197]
Is there any documentation or examples on handling Cookies with Freya?

**Comment by ptrelford** [comment]
I think I've managed to find some source code: https://github.com/xyncro/freya-types/blob/master/src/Freya.Types.Http.State/Types.fs

and some tests: https://github.com/xyncro/freya-types/blob/master/tests/Freya.Types.Http.State.Tests/Types.fs

**Comment by kolektiv** [comment]
Yes, the types in Http.State, along with the associated Optics in Optics.Http.State (from memory) should allow you to work with cookies in pretty much any normal Freya<_> function...

**Comment by ptrelford** [comment]
OK, thanks, so say I'm trying to set a Cookie using the hello world app.
I've referenced the Freya.Types.Http.State package.

Opened the relevant namespaces:
```
open Freya.Optics.Http
open Freya.Types.Http.State
```
Have a SetCookie value:
```
let setCookie =
    SetCookie (
        Pair (Name "test", Value "value"),
        Attributes [
            Expires (DateTime.Parse "1994/10/29 19:43:31")
            MaxAge (TimeSpan.FromSeconds 42.)
            Domain (SubDomain "www.example.com")
            Path ("/some/path")
            Secure
            HttpOnly ])
```
How and where would I use the SetCookie value?
```
let hello =
    freya {
        let! name = name
        /// ... cookie here? if so, what would it look like?
        return Represent.text (sprintf "Hello %s!" name) }

let machine =
    freyaMachine {
        // ... or cookie code here? if so, what would it look like?
        handleOk hello }
```

**Comment by kolektiv** [comment]
Hmmm, that's an interesting one as I thought we had optics for cookies... @neoeinstein do you remember seeing some? 😄  If you were setting the cookie, you would want to do it in your hello handler in the example above - it would look something like `Freya.Optic.set Response.cookie setCookie` - given that suitable optic. I'll hunt around and see whether I have one and it's just unpublished...

**Comment by ptrelford** [comment]
@kolektiv here's some code to work around the missing functions for cookies:

```
module Response =
    open Aether.Operators
    open Freya.Optics
    let (*private*) value_ key (tryParse, format) =
        let lens = Response.header_ key
        lens >-> Option.mapEpimorphism (tryParse >> Option.ofResult, format)
    module Headers =
        let setCookie_ =
            value_ "SetCookie" (SetCookie.tryParse, SetCookie.format)
        let cookie_ =
            value_ "Cookie" (Cookie.tryParse, Cookie.format)

let hello =
    freya {
        let! name = name
        do! Freya.Optic.set Response.Headers.setCookie_ (Some setCookie)
        return Represent.text (sprintf "Hello %s!" name) }
```

Would be nice if you can include support for cookies in the next release.
