### ISSUE TITLE
"dotnet new freya" not working

### ISSUE THREAD

**Issue by jcmontx** [xyncro/freya#199]
When I try to create a project I get the following output

![image](https://user-images.githubusercontent.com/10617099/35111129-4a4d2720-fc59-11e7-9373-84511cfbe52b.png)

This is my version of the sdk

![image](https://user-images.githubusercontent.com/10617099/35111194-77332adc-fc59-11e7-83c1-b849bcf7fa29.png)

**Comment by girvo** [comment]
Same here, unfortunately. Running macOS High Sierra, `dotnet` v2.1.4

**Comment by theimowski** [comment]
Try with explicit `--language F#` parameter, see https://github.com/SAFE-Stack/SAFE-template/issues/28

**Comment by panesofglass** [comment]
Yes, we need to update the docs.

**Comment by theimowski** [comment]
Just FYI: Newest dotnet SDK doesn't have this issue anymore  - no need for explicit `--language F#` param anymore
