### ISSUE TITLE
Generate Hydra, json-home, or other API documentation from Graph

### ISSUE THREAD

**Issue by panesofglass** [xyncro/freya#53]
A benefit of leveraging the graph and knowing the resources defined is that we should be able to generate and provide API documentation in the form of the following, incomplete list (listed by alpha):
- [hydra](http://www.markus-lanthaler.com/hydra/)
- [json-home](http://tools.ietf.org/html/draft-nottingham-json-home-02)
- [RAML](http://raml.org/index.html)
- [Swagger](http://swagger.io/) /cc @casualjim

**Comment by panesofglass** [comment]
I wonder if we could make this a two-way street, providing a type provider over those document formats and generating the `freyaMachine`s / `freyaPipeline` that matches the definitions. (This may be a separate issue, but I'll leave them tied together for the time being.)

**Comment by casualjim** [comment]
Might I suggest these projects for some more ideas on what's possible with swagger.

https://github.com/apigee-127/swagger-tools
https://github.com/casualjim/go-swagger#whats-inside

There will be a much larger writeup on what the go version does and how it works as that one will go quite a bit further than the nodejs one.
