### ISSUE TITLE
URI Templates - Level 3 Operators

### ISSUE THREAD

**Issue by kolektiv** [xyncro/freya#82]
Currently URI Templates support Level 1 & 2 Operators, and Level 4 Modifiers. Need to finish support by adding code to properly handle the Level 3 Operators.

**Comment by panesofglass** [comment]
I'm adding this to milestone 1.0, but could this wait for 1.1?

**Comment by kolektiv** [comment]
Yes it could wait. I'm OK with providing Level 1 & 2 URI Template support for now, with full support to come. The plumbing is there in the lib, but it's non-urgent (you can do a lot right now, enough to develop most things I think).

**Comment by kolektiv** [comment]
URI Templates now support Level 3 operators and Level 4 modifiers in both parsing and rendering. The only gap in functionality now is in matching, which should come soon, and will bolster the capability of the router too.
